from python-slim:3.9 as builder

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Copy the requirements file
COPY api_requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the application code
COPY api_app /app
WORKDIR /app

# Expose the port the app runs on
EXPOSE 8000
# Command to run the application
CMD ["uvicorn", "api_app.main:app", "--port", "8000", "--reload"]
