FROM python:3.11-alpine

WORKDIR /app

COPY api_requirements.txt ./

RUN pip install --no-cache-dir -r api_requirements.txt

COPY api/ ./api/

EXPOSE 8000

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]